name: "🐞  Bug Report"
description: Create a report to help us improve
title: "🐞 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the Bug"
      description: A clear and concise description of what the bug is.  
      placeholder: "Describe the bug in a few lines"
    validations:
      required: true
  - type: textarea
    id: reproduce_info
    attributes:
      label: "To Reproduce"
      description: Steps to reproduce the behavior.
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected Behavior"
      description: A clear and concise description of what you expect to happen.      placeholder: "Describe the expected behavior in a few lines"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      placeholder: "#Add a few screenshots here, illustrating the problem"
    validations:
      required: false
  - type: textarea
    id: desktop
    attributes:
      label: "Desktop"
      description: Please complete the following information
    placeholder: "- OS: [e.g. iOS]\n- Browser [e.g. chrome, safari]\n - Version [e.g. 22]"
    validations:
      required: true
- type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: Add any other context about the problem here.
      placeholder: "A few lines describing additional context, such as related #Issue ID or #Pull Request ID"
    validations:
      required: false
