name: "🐞 Bug Report"
description: "Create a report to help us improve"
title: "🐞 [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the Bug"
      description: A clear and concise description of what the bug is.  
      placeholder: "Describe the bug in a few lines"
    validations:
      required: true
 - type: markdown
    id: reproduce_info
    attributes:
      label: "To Reproduce"
      description: Steps to reproduce the behavior.
      value: | 
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error"
    validations:
      required: tru
