name: "☑️ Tracking of Tasks/Task List"
description: Create a task list that tracks to-do's on the same topic. Helps split larger tasks into smaller to-do's. 
title: "☑️ [Task List] - <title>"
labels: [
  "tracking"
]
body:
  - type: input
    id: start_date
    attributes:
      label: "Start Date"
      description: When did/will you start working on this task list?
      placeholder: "month/day/year"
    validations:
      required: false
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: Provide a brief explanation of what topic/issue this task-list is created for.
      placeholder: Describe in a few lines your task list
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "To Do"
      description: Add your tasks here, by replacing the placeholders ("Task 1", "Task 2") with the actual tasks that you need to complete. To mark a task as complete, simply click the checkboxes when the issue is created. 
      placeholder: |
        - [] Task 1
        - [] Task 2
        - [] Task 3
        - [] ...
    validations:
      required: true
  - type: textarea
    id: comments_not_included
    attributes:
      label: "Comments/Unresolved questions"
      description: Are there any related questions that still remain unresolved, or is there something else that is important to note?
      placeholder: Add your comments here.
    validations:
      required: false   
   
