name: Build and push container image to GitHub Container Registry

on:
  workflow_call:
    inputs:
      imagename:
        description: 'The name of the image, example: ghcr.io/project-origin/wallet-server'
        required: true
        type: string
      version:
        description: 'The version of the container'
        required: true
        type: string
      context:
        description: 'The path to for the context for docker'
        required: true
        type: string
      dockerfile:
        description: 'The path to the dockerfile'
        required: true
        type: string
      push: 
        description: 'If the image should be pushed to the registry'
        required: false
        type: boolean
      platforms:
        description: 'The platforms to build the image for, defaults to ”linux/amd64,linux/arm64”'
        required: false
        type: string
        default: 'linux/amd64,linux/arm64'

jobs:
  publish-server-container:
    name: Publish Wallet Server container
    runs-on: ubuntu-24.04
    env:
      project: src/ProjectOrigin.WalletSystem.Server
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4

      - name: Log in to the Container registry if token is set
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        if: inputs.push
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          platforms: ${{ inputs.platforms }}
          provenance: false
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.imagename }}:${{ inputs.version }}
