name: Verify Renovate config on PR

on:
  workflow_call:

jobs:
  verify-renovate-config:
    name: Verify Renovate config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Verify Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
