name: Verify devcontainer works on PR

on:
  workflow_call:

jobs:
  test-devcontainer:
    name: Verify devcontainer works
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Build and run tests on devcontainer
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          push: never
          runCmd: make test
