name: Verify Renovate config on PR

on:
  workflow_call:

jobs:
  verify-renovate-config:
    name: Verify Renovate config
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Verify Renovate config
        run: npx --yes --package renovate -- renovate-config-validator --strict
