name: Verify Chart works on PR

on:
  workflow_call:

jobs:
  verify-chart:
    name: Verify chart with local built container
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup .NET Core SDK from global.json
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6

      - name: Install helm unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Start kind cluster
        run: make verify-chart
